[tool.poetry]
name = "teaching"
version = "0.1.0"
description = ""
authors = ["Tanwa Arpornthip <72845369+CommanderCrowCode@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
opencv-python = "^4.9.0.80"
pillow = "^10.3.0"
flamingotools = {git = "git@github.com:CommanderCrowCode/FlamingoTools.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
